### ISSUE TITLE
on javascript

### ISSUE THREAD

**Issue by luigicallero** [cryptopunksnotdead/cryptopunks#2]
Hi Gerald,
Do you have these great scripts by any chance in js? I know ruby is a great coding language but it is in my todo list ;)

**Comment by geraldb** [comment]
Sorry, no. The scripts are written / coded in ruby.  The pixel editor (started by Ponder Ware of Mooncats fame) is in js, see <https://github.com/cryptopunksnotdead/cryptopunksnotdead.github.io>.  PS: You are invited to ask for js cryptopunk scripts on the cryptopunksdev channel @ <https://old.reddit.com/r/CryptoPunksDev/>.

**Comment by luigicallero** [comment]
Hey Gerard,

Was not expecting a reply so soon. Thanks for your promptness!!!

I will check the option you provided
