### ISSUE TITLE
It's hard to convert any cryptopunk into css matrice code ? 

### ISSUE THREAD

**Issue by kwizfreak** [cryptopunksnotdead/cryptopunks#4]
I want to use the same to generate cryptopunk in css not in png, it's hard to generate the matrice and use an array in css/scss to attribute color ? 
Thanks you :))

**Comment by geraldb** [comment]
Pease explain what you mean by "generate in css"? Do you mean named-colors instead of hex codes? Or something else?
       
Please, post your question (and explanations) to the CryptoPunksDev forum / channel @ <https://old.reddit.com/r/CryptoPunksDev>  Thanks.

**Comment by kwizfreak** [comment]
Sorry i got an issue to post on reddit but my idea is simple : 

I want to create a script in js / scss / html to generate cryptopunk 
you can see my idea : 
https://codepen.io/kwizfreak/pen/MWmGxKP
Now i need to generate the map color + matrice like 
https://github.com/cryptopunksnotdead/cryptopunks/tree/master/cryptopunks
And I want to combine the matrice + map colors to generate with js + scss the cryptopunkCSS
Who want to help me ? 
-> the goal is to create a function like in ruby 
cryptopunkcss(cryptopunk_id){
generate the matrice from png 
generate the color map from png 
generate the scss/html 
display 
}
Thanks you !
