### ISSUE TITLE
CryptoPunks GUI 0.0.15 setup fail on windows

### ISSUE THREAD

**Issue by texolli** [cryptopunksnotdead/cryptopunks#5]
Hello, I am quite a noob at this! Sorry for dumb question.
I've done all prerequities you need to make on windows. But i got a problem when i started to setup CryptoPunks GUI. I get this error and i am not sure how to fix this:
![image](https://github.com/cryptopunksnotdead/cryptopunks/assets/66481006/cd1591b9-b118-406e-9def-bf285af0b028)

**Comment by geraldb** [comment]
sorry that's out of my expertice.  maybe the author of the cryptopunks gui @AndyObtiva can help.

**Comment by texolli** [comment]
issue is solved, just my stupid mistake.
