### ISSUE TITLE
How can this shadow like effect be achieved?

### ISSUE THREAD

**Issue by zkung** [cryptopunksnotdead/cryptopunks#6]
![Snipaste_2022-04-01_12-20-34](https://user-images.githubusercontent.com/42948270/161194656-ab3d0cf8-1087-4118-abcb-28e3dfb50cbe.png)

**Comment by zkung** [comment]
I have been looking for a long time without finding an example.

**Comment by geraldb** [comment]
@zkung  Please post your question (e.g. how can this shadow like effect be achieved?) to the official public forum => <https://old.reddit.com/r/CryptoPunksDev/>       Thanks.
